
services:
  # 1. 프론트엔드 서비스 (이름: app)
  app:
    # my-app 폴더의 Dockerfile을 사용
    build: ./my-app
    ports:
      # 내 PC의 8080 포트와 컨테이너의 80 포트를 연결
      - "8080:80"
    # 'api' 서비스가 먼저 실행된 후에 'app'이 실행되도록 의존성 설정
    depends_on:
      - api

  # 2. 백엔드 서비스 (이름: api)
  api:
    # my-api 폴더의 Dockerfile을 사용
    build: ./my-api
    ports:
      # 내 PC의 5000 포트와 컨테이너의 5000 포트를 연결
      - "5000:5000"
    # (선택 사항) .env 파일을 사용해 환경 변수 주입
    # env_file:
    #   - ./my-api/.env
